### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by DeadOblivion78** [arichorn/uYouPlusExtra#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 17.0.3
- Device model: iPad Pro (11-inch) (3rd generation)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloady
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): uYouPlusExtra_18.44.3_3.0.1

### Describe the bug

App crashes as soon I play a YouTube short.

### Steps to reproduce the issue

1. Play a short.
2. App crashes to homescreen.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Can't paste in error log because error log is too long.
Error log here in pastebin.
https://pastebin.com/MqkYe92h

**Comment by stinkzies** [comment]
This is still present in the latest release

**Comment by IncursionX** [comment]
I believe I fixed this by turning on the “Remove the modern ui” setting in settings > uyouolus > miscellaneous

**Comment by Lazycaker** [comment]
I am still have this issue with the latest release (v18.48.3-3.0.1)

**Comment by Lazycaker** [comment]
this is STILL broken :/ 
Don't know if sharing my crash report will help

**Comment by MartinLoner** [comment]
Mine fixed by disabling Hide 'Buy Super Thanks' banner, Settings -> uYouEnhanced -> Shorts Controls Overlay Options
